### ISSUE TITLE
Crear la viborita

### ISSUE THREAD

**Issue by CharoLertora** [claram97/aninfo#13]
El objetivo es generar todos la lógica necesaria para que la viborita funcione en los distintos modos de juego:

- [x] Generar la viborita.
- [x] Generar que se pueda mover a 90°.
- [x] Generar que se pueda mover libremente (con flechitas y a futuro con mouse).
- [x] Generar que se pueda mover invertidamente.
- [x] Generar que crezca cada vez que se recoja un objeto.
- [x] Lograr que se pueda aumentar su velocidad de movimiento.
- [x] Hacer que muera cada vez que se choca con algo o se come a sí misma.

**Comment by fe-martinez** [comment]
Todo listo
