### ISSUE TITLE
Crear el modo de juego de laberinto.

### ISSUE THREAD

**Issue by CharoLertora** [claram97/aninfo#15]
El objetivo de este issue es crear por completo el modo de juego de laberinto:
Preguntas: lo vamos a hacer con niveles? el terreno se va a agrandar a medida que pasa los niveles? Tiene un final o la idea es que vaya recogiendo objetos y hayan paredes en el medio? Metodo de pasar de nivel si hay niveles?

- [x] Invocar método para generar terreno de juego y sumarle paredes al campo.
- [x] Hacer método que haga aparecer las paredes del laberinto.
- [x] Invocar método para mostrar la viborita por pantalla.
- [x] Invocar método para generar los objetos a recoger.
- [x] Llamar al método que incrementa la velocidad de la viborita a medida que pasa cierto lapso de tiempo.
- [x] Llamar al método que hace que la viborita se mueva a 90°.
- [x] Llamar al método que hace que la viborita crezca cada vez que recoja un objeto.
- [x] Mostrar un cartel cuando el jugador pierda que le indique: cantidad de objetos recogidos como puntaje y un mensaje de que finalizó el juego.

**Comment by ValentinSavarese** [comment]
va a haber "niveles" en base al score, por ejemplo cuando se llegue al score 5(no se si este va a ser el score final elegido) el tablero cambia de color y las paredes de lugar, lo mismo cuando se llegue al score 10(no se si este va a ser el score final elegido) y la idea es que despues sea infinito hasta que el jugador pierda.
