### ISSUE TITLE
Fix co-existencia de persistencia y tocar 'z' para empezar un nuevo juego

### ISSUE THREAD

**Issue by claram97** [claram97/aninfo#53]
Antes, al finalizar el juego, en la pantalla del final, si se tocaba la 'z' empezaba de nuevo el juego en el modo actual.
Ahora, por la persistencia, se puede empezar un juego que estaba guardado.
La existencia de la persistencia rompe el correcto funcionamiento de la tecla 'z'.
Ambas funcionalidades deberían poder co-existir.

**Comment by fe-martinez** [comment]
Solucionado
