### ISSUE TITLE
Agregar la persistencia a los otros modos

### ISSUE THREAD

**Issue by claram97** [claram97/aninfo#54]
Replicar en los otros modos lo que sucede en el modo de un jugador: al cerrar el juego, se guarda el estado actual. Al volver a elegir el modo, se le pregunta al usuario si se quiere continuar con el juego guardado o comenzar uno nuevo.

**Comment by fe-martinez** [comment]
Agregada la persistencia a 4 de los modos (normal, libre, 2 jugadores y laberinto)
